/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate and get JWT tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh JWT tokens using a refresh token.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get the current authenticated user's information.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Current User Profile
         * @description Update the current authenticated user's profile.
         */
        patch: operations["update_current_user_profile_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Markets
         * @description List markets with optional filtering and pagination.
         *
         *     Returns a paginated list of markets with their outcomes. Markets are ordered
         *     by last update time (most recent first).
         *
         *     - **category**: Filter by event category (exact match)
         *     - **search**: Search text in market question and description (case-insensitive)
         *     - **resolved**: Filter by resolved status (true/false)
         *     - **limit**: Maximum number of markets to return (1-500, default 50)
         *     - **offset**: Number of markets to skip for pagination
         */
        get: operations["list_markets_api_v1_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/advanced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Markets Advanced
         * @description List markets with real-time CLOB bid/ask data.
         *
         *     Returns a paginated list of markets enriched with order book data from
         *     the Polymarket CLOB API. This endpoint is suitable for advanced filtering
         *     and screening use cases.
         *
         *     **Sort options:**
         *     - `volume`: Sort by 24-hour trading volume (default)
         *     - `liquidity`: Sort by estimated liquidity
         *     - `spread`: Sort by bid-ask spread
         *     - `priceChange`: Sort by 24-hour price change magnitude
         *
         *     **Advanced filters:**
         *     - Volume range filters (minVolume, maxVolume)
         *     - Liquidity range filters (minLiquidity, maxLiquidity)
         *     - Spread range filters in cents (minSpread, maxSpread)
         *     - Price change filters (minChange, maxChange)
         *
         *     **CLOB data fields:**
         *     - `bid`: Best bid price (0-1)
         *     - `ask`: Best ask price (0-1)
         *     - `spread`: Absolute spread (ask - bid)
         *     - `spreadPercent`: Spread as percentage of midpoint
         *     - `spreadCents`: Spread in cents
         *     - `volume24h`: 24-hour trading volume in USD
         *     - `priceChange24h`: 24-hour price change
         *
         *     Note: CLOB data is cached for 30 seconds to reduce API calls.
         */
        get: operations["list_markets_advanced_api_v1_markets_advanced_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Markets Screener
         * @description Market screener with time-based filtering.
         *
         *     Returns markets with aggregated price change and volume metrics calculated
         *     over a specified time window. This endpoint is optimized for screening
         *     markets based on recent performance.
         *
         *     **Time windows:**
         *     - `6h`: Last 6 hours (uses daily data - hourly not yet available)
         *     - `12h`: Last 12 hours (uses daily data - hourly not yet available)
         *     - `24h`: Last 24 hours
         *     - `7d`: Last 7 days
         *
         *     **Sort options:**
         *     - `volume`: Sort by trading volume over the time window
         *     - `priceChange`: Sort by absolute price change magnitude
         *
         *     **Filters:**
         *     - Volume range filters (minVolume, maxVolume)
         *     - Price change filters as decimals (minPriceChange, maxPriceChange)
         *       - Use -0.1 for -10% and 0.1 for +10%
         *
         *     **Response fields:**
         *     - `volume24h`: Volume over the selected time window (not necessarily 24h)
         *     - `priceChange24h`: Price change over the selected time window
         *
         *     Note: Sub-daily time windows (6h, 12h) currently return daily data
         *     since hourly price marks are not yet available. This will be enhanced
         *     when hourly data is computed from Silver trades.
         */
        get: operations["list_markets_screener_api_v1_markets_screener_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description List all available tags (categories) for filtering markets.
         *
         *     Returns a list of categories with their market counts, ordered by the number
         *     of markets in each category (highest first). These can be used to populate
         *     filter dropdowns in the frontend.
         *
         *     **Response fields:**
         *     - `id`: Unique identifier for the tag (slug-based)
         *     - `name`: Display name of the category
         *     - `slug`: URL-friendly version of the name
         *     - `marketCount`: Number of markets in this category
         */
        get: operations["list_tags_api_v1_markets_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market
         * @description Get a single market by ID.
         *
         *     The market_id can be any of:
         *     - Internal market ID (platform_market_id)
         *     - Polymarket ID (same as platform_market_id for Polymarket markets)
         *     - Market slug (URL-friendly identifier)
         *
         *     Returns the market with all its outcome details.
         */
        get: operations["get_market_api_v1_markets__market_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Market Trades
         * @description Get trades for a specific market.
         *
         *     Returns a paginated list of trades for the specified market. Trades are
         *     ordered by timestamp (most recent first).
         *
         *     The market_id can be any of:
         *     - Internal market ID (platform_market_id)
         *     - Polymarket ID (same as platform_market_id for Polymarket markets)
         *     - Market slug (URL-friendly identifier)
         *
         *     - **limit**: Maximum number of trades to return (1-1000, default 100)
         *     - **offset**: Number of trades to skip for pagination
         *     - **startDate**: Filter trades after this date (inclusive)
         *     - **endDate**: Filter trades before this date (inclusive)
         */
        get: operations["list_market_trades_api_v1_markets__market_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Price History
         * @description Get price history for a market.
         *
         *     Returns historical price data for charting. Data points are returned in
         *     chronological order (oldest first).
         *
         *     The market_id can be any of:
         *     - Internal market ID (platform_market_id)
         *     - Polymarket ID (same as platform_market_id for Polymarket markets)
         *     - Market slug (URL-friendly identifier)
         *
         *     **Interval support:**
         *     - `1d`: Daily price points (recommended)
         *     - `1w`: Weekly aggregated price points
         *     - `1h`, `4h`: Currently return daily data (hourly data not yet available)
         *
         *     **Response fields:**
         *     - `timestamp`: ISO date string
         *     - `price`: Mark price (VWAP or last trade price)
         *     - `volume`: Trading volume in USD for the period
         */
        get: operations["get_price_history_api_v1_markets__market_id__price_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Traders
         * @description List traders with optional search and sorting.
         *
         *     Returns a paginated list of traders with their aggregated PnL and trade statistics.
         *     Traders are joined with their historical PnL data from wallet_pnl_daily.
         *
         *     - **search**: Search by wallet address prefix (case-insensitive ILIKE)
         *     - **sortBy**: Field to sort by (smartScore, totalPnl, totalTrades, winRate)
         *     - **sortOrder**: Sort direction (asc or desc, default desc)
         *     - **limit**: Maximum number of traders to return (1-500, default 50)
         *     - **offset**: Number of traders to skip for pagination
         */
        get: operations["list_traders_api_v1_traders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traders/smart-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Smart Scores
         * @description Get smart trader scores and rankings.
         *
         *     Computes smart scores for traders based on their trading performance
         *     over the specified time window. Scores range from 0-100 and are based
         *     on four weighted components:
         *
         *     - **Accuracy (30%)**: Win rate on closed positions
         *     - **Consistency (25%)**: Trading regularity over the time period
         *     - **Sizing (25%)**: Volume traded (log scale)
         *     - **Timing (20%)**: ROI efficiency (return relative to volume)
         *
         *     Query Parameters:
         *     - **minScore**: Minimum smart score to include (0-100, default 0)
         *     - **limit**: Maximum number of traders to return (1-500, default 100)
         *     - **timeWindow**: Time period for calculation
         *       - `7d`: Last 7 days
         *       - `30d`: Last 30 days (default)
         *       - `90d`: Last 90 days
         *       - `all`: All-time
         *
         *     Traders must have at least 5 trades in the time window to receive a score.
         */
        get: operations["get_smart_scores_api_v1_traders_smart_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traders/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pnl Leaderboard
         * @description Get PnL leaderboard for a time period.
         *
         *     Returns a ranked list of traders by realized PnL for the specified period.
         *
         *     - **period**: Time period for aggregation
         *       - `1d`: Today only
         *       - `7d`: Last 7 days (default)
         *       - `30d`: Last 30 days
         *       - `all`: All-time
         *     - **limit**: Maximum number of entries (1-500, default 100)
         *
         *     Each entry includes:
         *     - Rank (1-indexed)
         *     - Trader address
         *     - Total PnL for the period
         *     - Trade count
         *     - Win rate (percentage)
         */
        get: operations["get_pnl_leaderboard_api_v1_traders_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traders/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trader
         * @description Get detailed information about a specific trader.
         *
         *     Returns trader metadata, current open positions with market details,
         *     and aggregated PnL statistics.
         *
         *     - **address**: Wallet address (normalized to lowercase)
         *
         *     Positions include:
         *     - Market question and outcome name
         *     - Quantity held and average cost
         *     - Current price from latest market marks
         *     - Unrealized PnL based on current price vs avg cost
         *
         *     Returns 404 if the trader is not found.
         */
        get: operations["get_trader_api_v1_traders__address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traders/{address}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trader Trades
         * @description Get trades for a specific trader.
         *
         *     Returns a paginated list of trades from the trader's transaction history,
         *     ordered by timestamp descending (newest first).
         *
         *     - **address**: Wallet address (normalized to lowercase)
         *     - **limit**: Maximum number of trades to return (1-1000, default 100)
         *     - **offset**: Number of trades to skip for pagination
         *     - **startDate**: Filter trades on or after this date (YYYY-MM-DD)
         *     - **endDate**: Filter trades on or before this date (YYYY-MM-DD)
         *     - **marketId**: Filter to trades in a specific market
         *
         *     Each trade includes:
         *     - Market question and outcome name
         *     - Side (BUY/SELL), price, quantity, USD value
         *     - Fees and realized PnL (if position was closed)
         */
        get: operations["list_trader_trades_api_v1_traders__address__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist
         * @description Get user's watchlist with market details.
         *
         *     Returns all markets in the user's watchlist, enriched with current
         *     market information including price and 24h change.
         */
        get: operations["get_watchlist_api_v1_watchlist_get"];
        put?: never;
        /**
         * Add Market To Watchlist
         * @description Add a market to user's watchlist.
         *
         *     Returns the created watchlist item. Returns 400 if already in watchlist.
         */
        post: operations["add_market_to_watchlist_api_v1_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Market From Watchlist
         * @description Remove a market from user's watchlist.
         *
         *     Returns 204 No Content on success, 404 if not in watchlist.
         */
        delete: operations["remove_market_from_watchlist_api_v1_watchlist__market_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracked-traders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tracked Traders
         * @description Get user's tracked traders with stats.
         *
         *     Returns all tracked traders with PnL, recent trade count, and smart score.
         *     Includes the user's tier limit for tracked traders.
         */
        get: operations["get_tracked_traders_api_v1_tracked_traders_get"];
        put?: never;
        /**
         * Add Tracked
         * @description Add a trader to user's tracked list.
         *
         *     Returns 403 if tier limit is exceeded.
         *     Returns 400 if trader is already tracked.
         */
        post: operations["add_tracked_api_v1_tracked_traders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracked-traders/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Get activity feed from tracked traders.
         *
         *     Returns recent trades from all tracked traders, ordered by timestamp DESC.
         */
        get: operations["get_activity_api_v1_tracked_traders_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracked-traders/{tracker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tracked Trader
         * @description Get a single tracked trader with detailed stats.
         *
         *     Returns 404 if not found or not owned by user.
         */
        get: operations["get_tracked_trader_api_v1_tracked_traders__tracker_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Tracked Trader
         * @description Remove a trader from user's tracked list.
         *
         *     Returns 204 No Content on success, 404 if not found.
         */
        delete: operations["delete_tracked_trader_api_v1_tracked_traders__tracker_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Tracked Trader
         * @description Update a tracked trader's custom name.
         *
         *     Returns 404 if not found or not owned by user.
         */
        patch: operations["patch_tracked_trader_api_v1_tracked_traders__tracker_id__patch"];
        trace?: never;
    };
    "/api/v1/trades/smart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Smart Trades
         * @description Get recent trades from smart traders.
         *
         *     Returns recent trades from traders with high smart scores (based on
         *     historical performance). Smart score is computed from PnL performance,
         *     with top traders scoring closer to 100.
         *
         *     - **minScore**: Minimum smart score threshold (0-100, default 70)
         *     - **minAmount**: Optional minimum USD value filter
         *     - **limit**: Maximum number of trades to return (1-200, default 50)
         *
         *     Each trade includes the trader's smart score in addition to trade details.
         */
        get: operations["list_smart_trades_api_v1_trades_smart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trades/whales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Whale Trades
         * @description Get recent large trades (whale trades).
         *
         *     Returns recent trades with USD value at or above the minimum amount,
         *     ordered by timestamp descending (newest first).
         *
         *     - **minAmount**: Minimum USD value threshold (default $10,000)
         *     - **limit**: Maximum number of trades to return (1-200, default 50)
         *
         *     Each trade includes the trader's total portfolio value when available.
         */
        get: operations["list_whale_trades_api_v1_trades_whales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description List events with optional filtering and pagination.
         *
         *     Returns a paginated list of events. Events are ordered by last update time
         *     (most recent first).
         *
         *     - **category**: Filter by event category (exact match)
         *     - **search**: Search text in event title and description (case-insensitive)
         *     - **status**: Filter by event status (e.g., 'active', 'resolved')
         *     - **limit**: Maximum number of events to return (1-500, default 50)
         *     - **offset**: Number of events to skip for pagination
         */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Get a single event by ID with associated markets.
         *
         *     The event_id can be any of:
         *     - Platform event ID (platform_event_id)
         *     - Event slug (URL-friendly identifier)
         *
         *     Returns the event with all its associated markets.
         */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EventListResponse
         * @description Paginated event list response.
         */
        EventListResponse: {
            /** Items */
            items: components["schemas"]["EventResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * EventResponse
         * @description Event response with associated markets.
         */
        EventResponse: {
            /** Id */
            id: string;
            /** Polymarketeventid */
            polymarketEventId: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Category */
            category?: string | null;
            /** Markets */
            markets?: components["schemas"]["MarketBase"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LeaderboardEntry
         * @description Entry in the PnL leaderboard.
         */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** Traderaddress */
            traderAddress: string;
            /** Pnl */
            pnl: number;
            /** Tradecount */
            tradeCount: number;
            /** Winrate */
            winRate: number;
        };
        /**
         * LeaderboardResponse
         * @description Leaderboard response with entries.
         */
        LeaderboardResponse: {
            /** Period */
            period: string;
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
            /** Generatedat */
            generatedAt: string;
        };
        /**
         * MarketAdvancedListResponse
         * @description Paginated advanced market list response.
         */
        MarketAdvancedListResponse: {
            /** Items */
            items: components["schemas"]["MarketAdvancedResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * MarketAdvancedResponse
         * @description Market response with CLOB bid/ask data.
         */
        MarketAdvancedResponse: {
            /** Id */
            id: string;
            /** Polymarketid */
            polymarketId: string;
            /** Conditionid */
            conditionId?: string | null;
            /** Slug */
            slug?: string | null;
            /** Question */
            question: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Resolved */
            resolved: boolean;
            /** Totalvolume */
            totalVolume: number;
            /** Liquidity */
            liquidity: number;
            /** Createdat */
            createdAt: string;
            /** Imageurl */
            imageUrl?: string | null;
            /** Outcomes */
            outcomes?: components["schemas"]["MarketOutcome"][];
            /** Bid */
            bid?: number | null;
            /** Ask */
            ask?: number | null;
            /** Spread */
            spread?: number | null;
            /** Spreadpercent */
            spreadPercent?: number | null;
            /** Spreadcents */
            spreadCents?: number | null;
            /**
             * Volume24H
             * @default 0
             */
            volume24h: number;
            /**
             * Pricechange24H
             * @default 0
             */
            priceChange24h: number;
        };
        /**
         * MarketBase
         * @description Base market information.
         */
        MarketBase: {
            /** Id */
            id: string;
            /** Polymarketid */
            polymarketId: string;
            /** Conditionid */
            conditionId?: string | null;
            /** Slug */
            slug?: string | null;
            /** Question */
            question: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Resolved */
            resolved: boolean;
            /** Totalvolume */
            totalVolume: number;
            /** Liquidity */
            liquidity: number;
            /** Createdat */
            createdAt: string;
            /** Imageurl */
            imageUrl?: string | null;
        };
        /**
         * MarketListResponse
         * @description Paginated market list response.
         */
        MarketListResponse: {
            /** Items */
            items: components["schemas"]["MarketResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * MarketOutcome
         * @description Outcome details for a market.
         */
        MarketOutcome: {
            /** Id */
            id: string;
            /** Tokenid */
            tokenId: string;
            /** Outcomename */
            outcomeName: string;
            /** Currentprice */
            currentPrice: number;
            /** Volume */
            volume: number;
        };
        /**
         * MarketResponse
         * @description Market response with outcomes.
         */
        MarketResponse: {
            /** Id */
            id: string;
            /** Polymarketid */
            polymarketId: string;
            /** Conditionid */
            conditionId?: string | null;
            /** Slug */
            slug?: string | null;
            /** Question */
            question: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Resolved */
            resolved: boolean;
            /** Totalvolume */
            totalVolume: number;
            /** Liquidity */
            liquidity: number;
            /** Createdat */
            createdAt: string;
            /** Imageurl */
            imageUrl?: string | null;
            /** Outcomes */
            outcomes?: components["schemas"]["MarketOutcome"][];
        };
        /**
         * PriceHistoryPoint
         * @description Single point in price history.
         */
        PriceHistoryPoint: {
            /** Timestamp */
            timestamp: string;
            /** Price */
            price: number;
            /** Volume */
            volume: number;
        };
        /**
         * PriceHistoryResponse
         * @description Response for price history endpoint.
         */
        PriceHistoryResponse: {
            /** Items */
            items: components["schemas"]["PriceHistoryPoint"][];
            /** Marketid */
            marketId: string;
            /** Outcomeid */
            outcomeId?: string | null;
            /** Interval */
            interval: string;
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
        };
        /**
         * SmartScoreComponents
         * @description Components that make up a smart score.
         */
        SmartScoreComponents: {
            /** Accuracy */
            accuracy: number;
            /** Consistency */
            consistency: number;
            /** Sizing */
            sizing: number;
            /** Timing */
            timing: number;
        };
        /**
         * SmartScoreListResponse
         * @description List of smart scores.
         */
        SmartScoreListResponse: {
            /** Items */
            items: components["schemas"]["SmartScoreResponse"][];
            /** Timewindow */
            timeWindow: string;
            /** Generatedat */
            generatedAt: string;
        };
        /**
         * SmartScoreResponse
         * @description Smart score response for a trader.
         */
        SmartScoreResponse: {
            /** Address */
            address: string;
            /** Smartscore */
            smartScore: number;
            components: components["schemas"]["SmartScoreComponents"];
        };
        /**
         * SmartTradeResponse
         * @description Trade response with smart score of the trader.
         */
        SmartTradeResponse: {
            /** Id */
            id: string;
            /** Traderaddress */
            traderAddress: string;
            /** Marketid */
            marketId: string;
            /** Marketquestion */
            marketQuestion: string;
            /** Outcomeid */
            outcomeId: string;
            /** Outcomename */
            outcomeName: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Usdvalue */
            usdValue: number;
            /** Fees */
            fees: number;
            /** Realizedpnl */
            realizedPnl?: number | null;
            /** Timestamp */
            timestamp: string;
            /** Smartscore */
            smartScore: number;
        };
        /**
         * TagResponse
         * @description Tag (category) information for filtering markets.
         */
        TagResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Marketcount */
            marketCount: number;
        };
        /**
         * TokenRefresh
         * @description Schema for token refresh request.
         */
        TokenRefresh: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * TokenResponse
         * @description Schema for JWT token response.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TrackedTraderActivity
         * @description Activity feed item for a tracked trader.
         */
        TrackedTraderActivity: {
            /**
             * Traderid
             * Format: uuid
             */
            traderId: string;
            /** Traderaddress */
            traderAddress: string;
            /** Customname */
            customName?: string | null;
            trade: components["schemas"]["prediction_data__api__traders__schemas__TradeResponse"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * TrackedTraderCreate
         * @description Request body for adding a tracked trader.
         */
        TrackedTraderCreate: {
            /** Traderaddress */
            traderAddress: string;
            /** Customname */
            customName?: string | null;
        };
        /**
         * TrackedTraderResponse
         * @description Tracked trader response.
         */
        TrackedTraderResponse: {
            /** Traderaddress */
            traderAddress: string;
            /** Customname */
            customName?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * TrackedTraderUpdate
         * @description Request body for updating a tracked trader.
         */
        TrackedTraderUpdate: {
            /** Customname */
            customName?: string | null;
        };
        /**
         * TrackedTraderWithStats
         * @description Tracked trader with stats from ClickHouse.
         */
        TrackedTraderWithStats: {
            /** Traderaddress */
            traderAddress: string;
            /** Customname */
            customName?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Totalpnl
             * @default 0
             */
            totalPnl: number;
            /**
             * Recenttrades
             * @default 0
             */
            recentTrades: number;
            /** Smartscore */
            smartScore?: number | null;
        };
        /**
         * TrackedTradersListResponse
         * @description Response for tracked traders listing.
         */
        TrackedTradersListResponse: {
            /** Items */
            items: components["schemas"]["TrackedTraderWithStats"][];
            /** Count */
            count: number;
            /**
             * Limit
             * @description Tier limit for tracked traders
             */
            limit: number;
        };
        /**
         * TradeListResponse
         * @description Paginated list of trades.
         */
        TradeListResponse: {
            /** Items */
            items: components["schemas"]["prediction_data__api__traders__schemas__TradeResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * TradeResponse
         * @description Trade record for a market.
         */
        TradeResponse: {
            /** Id */
            id: string;
            /** Traderaddress */
            traderAddress: string;
            /** Marketid */
            marketId: string;
            /** Outcomeid */
            outcomeId: string;
            /** Outcomename */
            outcomeName: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Price */
            price: number;
            /** Amount */
            amount: number;
            /** Usdvalue */
            usdValue: number;
            /** Txhash */
            txHash?: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * TraderDetailResponse
         * @description Detailed trader response with positions and stats.
         */
        TraderDetailResponse: {
            /** Address */
            address: string;
            /** Username */
            username?: string | null;
            /** Firstseen */
            firstSeen: string;
            /** Totalpnl */
            totalPnl: number;
            /** Realizedpnl */
            realizedPnl: number;
            /** Totaltrades */
            totalTrades: number;
            /** Wincount */
            winCount: number;
            /** Losscount */
            lossCount: number;
            /** Id */
            id: string;
            /** Smartscore */
            smartScore?: number | null;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
            /** Positions */
            positions?: components["schemas"]["TraderPosition"][];
            /** Tradecount */
            tradeCount: number;
            /** Winrate */
            winRate: number;
        };
        /**
         * TraderListResponse
         * @description Paginated list of traders.
         */
        TraderListResponse: {
            /** Items */
            items: components["schemas"]["TraderResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * TraderPosition
         * @description Current position held by a trader.
         */
        TraderPosition: {
            /** Marketid */
            marketId: string;
            /** Marketquestion */
            marketQuestion: string;
            /** Outcomeid */
            outcomeId: string;
            /** Outcomename */
            outcomeName: string;
            /** Quantity */
            quantity: number;
            /** Avgcost */
            avgCost: number;
            /** Currentprice */
            currentPrice: number;
            /** Unrealizedpnl */
            unrealizedPnl: number;
            /** Realizedpnl */
            realizedPnl: number;
        };
        /**
         * TraderResponse
         * @description Trader response with additional metadata.
         */
        TraderResponse: {
            /** Address */
            address: string;
            /** Username */
            username?: string | null;
            /** Firstseen */
            firstSeen: string;
            /** Totalpnl */
            totalPnl: number;
            /** Realizedpnl */
            realizedPnl: number;
            /** Totaltrades */
            totalTrades: number;
            /** Wincount */
            winCount: number;
            /** Losscount */
            lossCount: number;
            /** Id */
            id: string;
            /** Smartscore */
            smartScore?: number | null;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /**
         * UserCreate
         * @description Schema for user registration.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /**
         * UserLogin
         * @description Schema for user login.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Schema for user response (no password).
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            tier: components["schemas"]["UserTier"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserTier
         * @description User subscription tier.
         * @enum {string}
         */
        UserTier: "FREE" | "PRO";
        /**
         * UserUpdate
         * @description Schema for updating user profile.
         */
        UserUpdate: {
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchlistAddRequest
         * @description Request body for adding to watchlist.
         */
        WatchlistAddRequest: {
            /** Marketid */
            marketId: string;
        };
        /**
         * WatchlistItem
         * @description Base watchlist item schema.
         */
        WatchlistItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Marketid */
            marketId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * WatchlistItemWithMarket
         * @description Watchlist item with market details.
         */
        WatchlistItemWithMarket: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Marketid */
            marketId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Marketquestion */
            marketQuestion: string;
            /** Marketcategory */
            marketCategory?: string | null;
            /** Currentprice */
            currentPrice: number;
            /** Pricechange24H */
            priceChange24h: number;
            /** Resolved */
            resolved: boolean;
        };
        /**
         * WatchlistResponse
         * @description Response for watchlist listing.
         */
        WatchlistResponse: {
            /** Items */
            items: components["schemas"]["WatchlistItemWithMarket"][];
            /** Count */
            count: number;
        };
        /**
         * WhaleTradeResponse
         * @description Trade response with whale metadata.
         */
        WhaleTradeResponse: {
            /** Id */
            id: string;
            /** Traderaddress */
            traderAddress: string;
            /** Marketid */
            marketId: string;
            /** Marketquestion */
            marketQuestion: string;
            /** Outcomeid */
            outcomeId: string;
            /** Outcomename */
            outcomeName: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Usdvalue */
            usdValue: number;
            /** Fees */
            fees: number;
            /** Realizedpnl */
            realizedPnl?: number | null;
            /** Timestamp */
            timestamp: string;
            /** Totalwalletvalue */
            totalWalletValue: number;
        };
        /**
         * TradeListResponse
         * @description Paginated trade list response.
         */
        prediction_data__api__markets__schemas__TradeListResponse: {
            /** Items */
            items: components["schemas"]["TradeResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * TradeResponse
         * @description Trade record for a trader.
         */
        prediction_data__api__traders__schemas__TradeResponse: {
            /** Id */
            id: string;
            /** Traderaddress */
            traderAddress: string;
            /** Marketid */
            marketId: string;
            /** Marketquestion */
            marketQuestion: string;
            /** Outcomeid */
            outcomeId: string;
            /** Outcomename */
            outcomeName: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Usdvalue */
            usdValue: number;
            /** Fees */
            fees: number;
            /** Realizedpnl */
            realizedPnl?: number | null;
            /** Timestamp */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_current_user_profile_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_markets_api_v1_markets_get: {
        parameters: {
            query?: {
                /** @description Filter by category (exact match) */
                category?: string | null;
                /** @description Search in question and description */
                search?: string | null;
                /** @description Filter by resolved status */
                resolved?: boolean | null;
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_markets_advanced_api_v1_markets_advanced_get: {
        parameters: {
            query?: {
                /** @description Filter by category (exact match) */
                category?: string | null;
                /** @description Search in question and description */
                search?: string | null;
                /** @description Filter by resolved status */
                resolved?: boolean | null;
                /** @description Sort field */
                sortBy?: "volume" | "liquidity" | "spread" | "priceChange";
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
                /** @description Minimum 24h volume in USD */
                minVolume?: number | null;
                /** @description Maximum 24h volume in USD */
                maxVolume?: number | null;
                /** @description Minimum liquidity */
                minLiquidity?: number | null;
                /** @description Maximum liquidity */
                maxLiquidity?: number | null;
                /** @description Minimum spread in cents */
                minSpread?: number | null;
                /** @description Maximum spread in cents */
                maxSpread?: number | null;
                /** @description Minimum 24h price change */
                minChange?: number | null;
                /** @description Maximum 24h price change */
                maxChange?: number | null;
                /** @description Comma-separated tags to filter by */
                tags?: string | null;
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Page number (alternative to offset) */
                page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketAdvancedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_markets_screener_api_v1_markets_screener_get: {
        parameters: {
            query?: {
                /** @description Time window for volume and price change calculations */
                timeWindow?: "6h" | "12h" | "24h" | "7d";
                /** @description Filter by category (exact match) */
                category?: string | null;
                /** @description Search in question and description */
                search?: string | null;
                /** @description Filter by resolved status */
                resolved?: boolean | null;
                /** @description Sort field (volume or priceChange) */
                sortBy?: "volume" | "priceChange";
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
                /** @description Minimum volume in USD over the time window */
                minVolume?: number | null;
                /** @description Maximum volume in USD over the time window */
                maxVolume?: number | null;
                /** @description Minimum price change (e.g., -0.1 for -10%) */
                minPriceChange?: number | null;
                /** @description Maximum price change (e.g., 0.1 for +10%) */
                maxPriceChange?: number | null;
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketAdvancedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_markets_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
        };
    };
    get_market_api_v1_markets__market_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Market identifier (can be internal ID, polymarketId, or slug) */
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_market_trades_api_v1_markets__market_id__trades_get: {
        parameters: {
            query?: {
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter trades after this date (YYYY-MM-DD format) */
                startDate?: string | null;
                /** @description Filter trades before this date (YYYY-MM-DD format) */
                endDate?: string | null;
            };
            header?: never;
            path: {
                /** @description Market identifier (can be internal ID, polymarketId, or slug) */
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["prediction_data__api__markets__schemas__TradeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_price_history_api_v1_markets__market_id__price_history_get: {
        parameters: {
            query?: {
                /** @description Time interval for aggregation. Supported: 1h, 4h, 1d, 1w. Note: Currently only daily data is available, so 1h/4h return daily granularity. */
                interval?: string;
                /** @description Start date filter (YYYY-MM-DD format) */
                startDate?: string | null;
                /** @description End date filter (YYYY-MM-DD format) */
                endDate?: string | null;
                /** @description Specific outcome ID. Defaults to YES outcome if not specified. */
                outcomeId?: string | null;
            };
            header?: never;
            path: {
                /** @description Market identifier (can be internal ID, polymarketId, or slug) */
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traders_api_v1_traders_get: {
        parameters: {
            query?: {
                /** @description Search by wallet address prefix (case-insensitive) */
                search?: string | null;
                /** @description Field to sort by */
                sortBy?: "smartScore" | "totalPnl" | "totalTrades" | "winRate";
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_smart_scores_api_v1_traders_smart_scores_get: {
        parameters: {
            query?: {
                /** @description Minimum smart score to include */
                minScore?: number;
                /** @description Maximum entries to return */
                limit?: number;
                /** @description Time window for score calculation */
                timeWindow?: "7d" | "30d" | "90d" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartScoreListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pnl_leaderboard_api_v1_traders_leaderboard_get: {
        parameters: {
            query?: {
                /** @description Time period for leaderboard aggregation */
                period?: "1d" | "7d" | "30d" | "all";
                /** @description Maximum entries to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trader_api_v1_traders__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet address (case-insensitive, normalized to lowercase) */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraderDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trader_trades_api_v1_traders__address__trades_get: {
        parameters: {
            query?: {
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Filter trades on or after this date (YYYY-MM-DD) */
                startDate?: string | null;
                /** @description Filter trades on or before this date (YYYY-MM-DD) */
                endDate?: string | null;
                /** @description Filter to a specific market */
                marketId?: string | null;
            };
            header?: never;
            path: {
                /** @description Wallet address (case-insensitive, normalized to lowercase) */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_v1_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    add_market_to_watchlist_api_v1_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_market_from_watchlist_api_v1_watchlist__market_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tracked_traders_api_v1_tracked_traders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedTradersListResponse"];
                };
            };
        };
    };
    add_tracked_api_v1_tracked_traders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackedTraderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedTraderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_v1_tracked_traders_activity_get: {
        parameters: {
            query?: {
                limit?: number;
                startDate?: string | null;
                endDate?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedTraderActivity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tracked_trader_api_v1_tracked_traders__tracker_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedTraderWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tracked_trader_api_v1_tracked_traders__tracker_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tracked_trader_api_v1_tracked_traders__tracker_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackedTraderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedTraderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_smart_trades_api_v1_trades_smart_get: {
        parameters: {
            query?: {
                /** @description Minimum smart score (0-100) */
                minScore?: number;
                /** @description Minimum USD value of trade */
                minAmount?: number | null;
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartTradeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_whale_trades_api_v1_trades_whales_get: {
        parameters: {
            query?: {
                /** @description Minimum USD value of trade */
                minAmount?: number;
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhaleTradeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Filter by category (exact match) */
                category?: string | null;
                /** @description Search in title and description */
                search?: string | null;
                /** @description Filter by status (e.g., 'active', 'resolved') */
                status?: string | null;
                /** @description Maximum results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event identifier (can be platform_event_id or slug) */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
